name: 'Settings Tray'
type: module
description: 'Provides a sidebar to configure blocks on the page.'
package: Core
version: VERSION
core: 8.x
dependencies:
  - block
  - toolbar
  - contextual

# Information added by drush on 2018-08-01
version: '8.5.6'
project: 'drupal'
datestamp: 1533156642